version: '3'

services:
  db:
    image: postgres
    volumes:
       - ../django_data:/var/lib/postgresql/data
  web:
    build: .
    command: /bin/bash /code/docker-dev-entrypoint.sh
    volumes:
      - .:/code
      - ../logs:/code/logs/
      - ../media:/code/media/
    ports:
      - "8000:8000"
    depends_on:
      - db