version: '3'

services:
  db:
    image: postgres
    volumes:
       - ../django_data:/var/lib/postgresql/data
  web:
    image: abradle/fragalysis_stack
    command: ["/code/wait-for-it.sh", "db:5432", "--", "/bin/bash/", "/code/test_entry.sh]
    volumes:
      - .:/code
      - ../logs:/code/logs/
      - ../media:/code/media/
    ports:
      - "80:80"
    depends_on:
      - db