version: '3'

services:
  db:
    image: postgres
    volumes:
       - ../django_data:/var/lib/postgresql/data
  cartridge:
    image: informaticsmatters/rdkit_cartridge:Release_2017_09_1
    user: root
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ../cartridge_data:/var/lib/postgresql/data
  graph:
    container_name: neo4j
    image: neo4j
    ports:
# Comment these two out in produciton
      - "7474:7474"
      - "7687:7687"
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    volumes:
      - ../neo4j/data:/data
      - ../neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_pagecache_size=4G
  web:
    build: .
    command: /bin/bash /code/docker-entrypoint.sh
    volumes:
      - .:/code
      - ../logs:/code/logs/
      - ../media:/code/media/
    ports:
      - "80:80"
    depends_on:
      - db
      - graph
      - cartridge
      