version: '3'

services:
  db:
    image: postgres
    volumes:
     - /home/ec2-user/django_data:/var/lib/postgresql/data
  cartridge: 
    image: informaticsmatters/rdkit_cartridge:Release_2017_09_1
    user: root
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - /home/ec2-user/cartridge_data:/var/lib/postgresql/data
  jupyter:
    image: abradle/rdjupyter
    user: root
    ports:
      - "8888:8888"
    volumes:
      - /home/ec2-user/notebooks:/home/jovyan/
    command: start-notebook.sh --NotebookApp.token=''
    environment:
      - NB_UID=500
      - GRANT_SUDO=yes
  graph:
    image: neo4j
    ports:
# Comment these two out in produciton
      - "7474:7474"
      - "7687:7687"
    volumes:
      - /home/ec2-user:/data
    environment:
      - NEO4J_AUTH=none
  web:
    build: .
    command: /bin/bash /code/docker-entrypoint.sh
    volumes:
      - .:/code
      - /home/ec2-user/logs:/srv/logs/
      - /home/ec2-user/media:/srv/media/
    ports:
      - "8010:80"
    depends_on:
      - db
      - graph
      - cartridge
